### ISSUE TITLE
Exception in callback of async function: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by adamwong246** [VeliovGroup/Meteor-iron-router-meta#8]
```
Exception in callback of async function: TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (native)
    at Function._.has (http://localhost:3000/packages/underscore/underscore.js:1072:1)
    at [object Object].<anonymous> (http://localhost:3000/packages/ostrio:iron-router-meta/iron-router-meta.coffee:7:49)
    at http://localhost:3000/packages/iron:router/lib/router.js:277:1
    at [object Object]._.extend.withValue (http://localhost:3000/packages/meteor/dynamics_browser.js:23:1)
    at [object Object].Router.addHook.hookWithOptions (http://localhost:3000/packages/iron:router/lib/router.js:276:1)
    at [object Object].RouteController.runHooks (http://localhost:3000/packages/iron:router/lib/route_controller.js:180:1)
    at [object Object].RouteController._runRoute (http://localhost:3000/packages/iron:router/lib/route_controller_client.js:254:1)
    at Function.Route.dispatch (http://localhost:3000/packages/iron:router/lib/route.js:156:1)
    at [object Object].route (http://localhost:3000/packages/iron:router/lib/route.js:13:1)
```

**Comment by dr-dimitru** [comment]
Hi @adamwong246 what and to which method you're passing?
[line 7](https://github.com/VeliovGroup/Meteor-iron-router-meta/blob/master/iron-router-meta.coffee#L7) can throw an error only if iron-router is not installed.

**Comment by dr-dimitru** [comment]
Hi @adamwong246 any news from your end?

**Comment by dr-dimitru** [comment]
Closed due to no response from topic starter
